[tool.pylint.'MASTER']
ignore = "tests"
max-line-length = 100

[tool.pylint.'MESSAGES CONTROL']
disable = ["C0114", "C0115", "C0116"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
